import numpy as np

def generate_cube_lut(colors, size=17, output_path='output/cinematic_lut.cube'):
    # Simple approach: use a small 3D LUT grid and map identity -> a tint derived from palette
    # This is a lightweight heuristic LUT generator for demonstration.
    # The LUT maps input RGB to output RGB by applying a small color shift based on dominant color.
    dominant = colors[0] / 255.0  # take the first cluster as dominant tone (RGB)
    shift = (dominant - np.array([0.5,0.5,0.5])) * 1.25
 # mild shift

    with open(output_path, 'w') as f:
        f.write('# Generated by Cinematic LUT Generator\n')
        f.write('LUT_3D_SIZE {}\n'.format(size))
        for b in range(size):
            for g in range(size):
                for r in range(size):
                    rf = r / (size - 1)
                    gf = g / (size - 1)
                    bf = b / (size - 1)
                    out = np.array([rf, gf, bf]) + shift
                    out = np.clip(out, 0.0, 1.0)
                    f.write(f"{out[0]:.6f} {out[1]:.6f} {out[2]:.6f}\n")
    print(f".cube LUT written to {output_path}")
